### ISSUE TITLE
Possible change/regression in Gitlab v13 for group deletion?

### ISSUE THREAD

**Issue by ringods** [terraform-providers/terraform-provider-gitlab#319]
### Terraform Version
Unrelated to TF version.

### Affected Resource(s)
Please list the resources as a list, for example:
- gitlab_group

### Expected Behavior
Test should be working.

### Actual Behavior
Test is failing sometimes:

* 13.0.0: https://github.com/terraform-providers/terraform-provider-gitlab/runs/710870254
* 13.0.1: https://github.com/terraform-providers/terraform-provider-gitlab/runs/716102551

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://gitlab.com/gitlab-org/gitlab/-/issues/33257#note_352250521

**Comment by oboukili** [comment]
I have been doing some investigations as well as part of #318, the behaviour is erratic and it seems to be the groups API fault, I think it may use an invalid cache, as seen in the http responses sent to it:

failed test:

172.17.0.1 - - [01/Jun/2020:07:21:10 +0000] "POST /api/v4/groups HTTP/1.1" 201 741 "" "go-gitlab" -
172.17.0.1 - - [01/Jun/2020:07:21:10 +0000] "GET /api/v4/groups/34 HTTP/1.1" 200 780 "" "go-gitlab" -
172.17.0.1 - - [01/Jun/2020:07:21:10 +0000] "GET /api/v4/groups/34 HTTP/1.1" 200 780 "" "go-gitlab" -
172.17.0.1 - - [01/Jun/2020:07:21:10 +0000] "DELETE /api/v4/groups/34 HTTP/1.1" 202 26 "" "go-gitlab" -
**172.17.0.1 - - [01/Jun/2020:07:21:10 +0000] "GET /api/v4/groups/34 HTTP/1.1" 200 780 "" "go-gitlab" -**
172.17.0.1 - - [01/Jun/2020:07:21:10 +0000] "GET /api/v4/groups/34 HTTP/1.1" 404 33 "" "go-gitlab" -

successul test:

172.17.0.1 - - [01/Jun/2020:07:21:19 +0000] "POST /api/v4/groups HTTP/1.1" 201 746 "" "go-gitlab" -
172.17.0.1 - - [01/Jun/2020:07:21:19 +0000] "GET /api/v4/groups/35 HTTP/1.1" 200 785 "" "go-gitlab" -
172.17.0.1 - - [01/Jun/2020:07:21:19 +0000] "GET /api/v4/groups/35 HTTP/1.1" 200 785 "" "go-gitlab" -
172.17.0.1 - - [01/Jun/2020:07:21:19 +0000] "DELETE /api/v4/groups/35 HTTP/1.1" 202 26 "" "go-gitlab" -
172.17.0.1 - - [01/Jun/2020:07:21:19 +0000] "GET /api/v4/groups/35 HTTP/1.1" 404 33 "" "go-gitlab" -

Now, the results should actually be reversed, since  

We might be able to workaround it either by introducing a static waiting time 😨 , or better, if the group API response exposed some header indicating the cache freshness we could act on it.
